[build]
  publish = "REMS/public"
  command = "hugo -s REMS"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/themes"
  HUGO_VERSION = "0.72.0"

[context.production.environment]
  HUGO_BASEURL = "hugo -s REMS -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo -s REMS -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"

[context.branch-deplpy]
  command = "hugo -s exampleSite -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"
